
tasks:
  - before: |
      pip install --upgrade pip
      pip install poetry
      poetry config virtualenvs.create false --local
    init: poetry install
    command: poetry shell

vscode:
  extensions:
    - ms-python.python
