instance:
  _target_: pytorch_lightning.Trainer
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0.0
  gradient_clip_algorithm: norm
  num_processes: 1
  gpus: 1
  log_gpu_memory: null
  overfit_batches: 0.0
  fast_dev_run: false
  max_epochs: 20
  min_epochs: 4
  log_every_n_steps: 150
  precision: 16
  num_sanity_val_steps: 2
  profiler: null
  auto_lr_find: false

loggers:
  tensorboard:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: "tensorboard/"
    default_hp_metric: false
    name: ""
    version: ""
    log_graph: false
    prefix: ""
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    entity: "butterflies"
    project: "session-a"
    offline: false
    id: null # pass correct id to resume experiment!
    log_model: false
    prefix: ""
    job_type: "train"
    group: ""
    tags: [ ]

callbacks:
  checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "epoch-val-loss"
    dirpath: "checkpoints/"
    save_last: true
    filename: "{epoch:03}-{epoch-val-loss:.4f}"
    save_top_k: 1
  lr_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step
    log_momentum: true
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: "epoch-val-loss"
    patience: 1
    check_on_train_epoch_end: false
