optimizer:
  _target_: torch.optim.Adam
  lr: 0.0003
  weight_decay: 0.0

loss:
  _target_: torch.nn.CrossEntropyLoss
  label_smoothing: 0.0

loss_weights:
  - 6
  - 1
  - 1
  - 1

unfreeze_backbone_epoch_start: 0
unfreeze_backbone_epoch_duration: 0
unfreeze_backbone_percentage: 0.0

metrics:
  - _target_: torchmetrics.Accuracy
    average: micro
  - _target_: torchmetrics.Precision
    average: macro
  - _target_: torchmetrics.Recall
    average: macro
  - _target_: torchmetrics.F1
    average: macro
