device: "cpu"

optimizer:
  _target_: torch.optim.Adam
  lr: 0.003
  weight_decay: 0.0001

loss:
  _target_: torch.nn.CrossEntropyLoss

#data_mix:
#  mode: MIXUP
#  probability: 1.0
#  alpha: 0.5

loss_weights:
  - 1
  - 1
  - 1
  - 1

metrics:
  - _target_: torchmetrics.Accuracy
    average: micro
  - _target_: torchmetrics.Precision
    average: macro
  - _target_: torchmetrics.Recall
    average: macro
  - _target_: torchmetrics.F1
    average: macro
