device: "cuda:0"

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0003
  weight_decay: 0.0001

unfreeze_backbone_epoch: 0

loss:
  _target_: torch.nn.CrossEntropyLoss

loss_weights:
  - 1
  - 1
  - 1
  - 1

metrics:
  - _target_: torchmetrics.Accuracy
    average: micro
  - _target_: torchmetrics.Precision
    average: macro
  - _target_: torchmetrics.Recall
    average: macro
  - _target_: torchmetrics.F1
    average: macro
