defaults:
  - _self_
  - code_config
  - data: dev
  - model: dev
  - lit: dev
  - trainer: dev

seed: 31415
debug: true
test: false

# @package data
data_path: test_data/image_folder
label_hierarchy_file: data/family.csv
