defaults:
  - default
  - _self_

tune: false

data:
  data_path: test_data/image_folder
  label_hierarchy_file: data/family.csv
  test_fraction: 0.25
  batch_size: 4
  num_workers: 0
  pin_memory: false
  min_samples: 4

trainer:
  instance:
    gpus: null
    max_epochs: 1
    min_epochs: 1
    log_every_n_steps: 5

  loggers:
    wandb:
      project: dev
