defaults:
  - default
  - _self_
  - override hydra/sweeper: ax

hydra:
  sweeper:
    ax_config:
      max_trials: 4

      experiment:
        minimize: true

      early_stop:
        max_epochs_without_improvement: 2

      is_noisy: true

      params:
        data.min_samples:
          type: range
          value_type: int
          bounds: [ 100, 500 ]
        data.weighted_sampling:
          type: choice
          value_type: bool
          values: [ true, false ]
        data.weighted_sampling_fraction:
          type: range
          value_type: float
          bounds: [ 0.0, 0.1 ]
#        model.zoo_name:
#          type: choice
#          value_type: str
#          values: [ efficientnet_b7 ]
        lit.loss.label_smoothing:
          type: range
          value_type: float
          bounds: [ 0.0, 0.1 ]
        lit.loss_weights.0:
          type: range
          value_type: int
          bounds: [ 1, 10 ]
#        lit.unfreeze_backbone_epoch_start:
#          type: range
#          value_type: int
#          bounds: [ 0, 2 ]
        lit.unfreeze_backbone_epoch_duration:
          type: range
          value_type: int
          bounds: [ 0, 4 ]
        lit.unfreeze_backbone_percentage:
          type: range
          value_type: float
          bounds: [ 0.0, 0.5 ]
