optimizer:
  _target_: torch.optim.Adam
  lr: 0.0022908676527677745
  weight_decay: 0.0

loss:
  _target_: torch.nn.CrossEntropyLoss
  label_smoothing: 0.003932545799762011

loss_weights:
  - 5
  - 1
  - 1
  - 1

unfreeze_backbone_epoch_start: 1
unfreeze_backbone_epoch_duration: 4
unfreeze_backbone_percentage: 0.4

metrics:
  - _target_: torchmetrics.Accuracy
    average: micro
  - _target_: torchmetrics.Precision
    average: macro
  - _target_: torchmetrics.Recall
    average: macro
  - _target_: torchmetrics.F1
    average: macro
